/*

fstprintpaths.hpp

traverses an fst and prints out all of the paths in that fst along with the costs.

output format is: WORD cost X.XX

where WORD is a sequence of characters accepted or generated by the fst AND X.XX 
is a floating point value representing the cost of traversing that structure.

author: chris taylor

OpenFst forum post title: "Natural code for printing all strings accepted by an FST?"
OpenFst forum post link: http://openfst.cs.nyu.edu/twiki/bin/view/Forum/FstForum#Natural_code_for_printing_all_st

*/

#ifndef __FSTPATHFINDER__
#define __FSTPATHFINDER__

#include <fst/fstlib.h>

using namespace fst;

typedef struct PathData{
  vector<string> path;
  TropicalWeight pathcost;
};

class FstPathFinder{
  public:
    
  vector<PathData> paths;

  enum ProjectionEnum { PROJECT_INPUT, PROJECT_OUTPUT } ;

  void findAllStrings(StdVectorFst& fst, SymbolTable& st, string& seqToSkip, ProjectionEnum printInputOrOutput = PROJECT_OUTPUT);

  void findAllStringsHelper(StdVectorFst& fst, SymbolTable& st, int state, vector<string>& str, TropicalWeight cost, string& seqToSkip, ProjectionEnum printInputOrOutput=PROJECT_OUTPUT); 

}; // end class

#endif

